simulation:
    tick_time: 1
    max_steps: 5000
    dt: 0.01
    force_model: lennard.Lennard
    boundary: wall

box:
    width: 10
    height: 10

canvas:
    width: 500
    height: 500
    radius: 2

molecules:
    - r: [4,4]
      v: [0,0]
    - r: [6,4]
      v: [0,0]
    - r: [5,5.7320508075688772935274463415058723669428052538103805]
      v: [0,0]
