simulation:
    tick_time: 1
    max_steps: 10000
    dt: 0.001
    force_model: lennard.Lennard
    boundary: wall

box:
    width: 3
    height: 3

canvas:
    width: 500
    height: 500
    radius: 2

molecules:
    - r: [1,1]
      v: [0,0]
      # 2.122 = 2^(1/6) = equilibrium point
    - r: [1,2.1224620483093729814335330496791795162324111106139867]
      v: [0,0]
