simulation:
    tick_time: 1
    max_steps: 5000
    dt: 0.01
    force_model: lennard.Lennard
    boundary: wall

box:
    width: 10
    height: 10

canvas:
    width: 500
    height: 500
    radius: 2

molecules: grid
molecules_args:
    x_num: 5
    y_num: 5
    y_scale: 0.5
