simulation:
    tick_time: 1
    max_steps: 5000
    dt: 0.01
    force_model: lennard.Lennard
    boundary: wall

box:
    width: 10
    height: 10

canvas:
    width: 500
    height: 500
    radius: 2

molecules:
    - r: [4,1]
      v: [0,0]
    - r: [5,1]
      v: [0,0]
    - r: [6,1]
      v: [0,0]
    - r: [7,1]
      v: [0,0]
    - r: [8,1]
      v: [0,0]
