simulation:
    tick_time: 1
    max_steps: 5000
    dt: 0.001
    force_model: lennard.Lennard
    boundary: wall

box:
    width: 3
    height: 3

canvas:
    width: 500
    height: 500
    radius: 2

molecules:
    - r: [0.5,1]
      v: [0,0]
    - r: [2.5,1]
      v: [0,0]
