simulation:
    tick_time: 1
    dt: 0.01
    force_model: lennard.Lennard

box:
    width: 3
    height: 3

canvas:
    width: 500
    height: 500
    radius: 2

molecules:
    - r: [1,1]
      v: [0,0]
    - r: [3,3]
      v: [0,0]
